#file: noinspection UndefinedParamsPresent,UndefinedAction,SpellCheckingInspection
name: Run Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    run-tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                include:
                    -   php-version: '8.2'
                        laravel: '^12.0'
                    -   php-version: '8.4'
                        laravel: '^13.0'

        steps:
            -   uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: mbstring, pdo_sqlite, zip, curl

            -   name: Require Laravel ${{ matrix.laravel }}
                run: composer require "illuminate/database:${{ matrix.laravel }}" "illuminate/support:${{ matrix.laravel }}" --no-update

            -   name: Install Dependencies
                run: composer update --prefer-dist --no-progress -W

            -   name: Copy .env
                run: cp .env.example .env

            -   name: Run Tests
                run: vendor/bin/phpunit --configuration phpunit.xml
